/*
 * This copyright notice applies to this header file only:
 *
 * Copyright (c) 2010-2018 NVIDIA Corporation
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the software, and to permit persons to whom the
 * software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated with bindgen 0.72.1 from NVIDIA/video-sdk-samples
// aa3544dcea2fe63122e4feb83bf805ea40e58dbe, cuviddec.h (SDK 8.1).
// Data ABI only; no linked symbols or build-time SDK/FFmpeg dependency.
#![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals,
    unnecessary_transmutes, unsafe_op_in_unsafe_fn, clippy::undocumented_unsafe_blocks)]
/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDH264DPBENTRY {
    pub PicIdx: ::std::os::raw::c_int,
    pub FrameIdx: ::std::os::raw::c_int,
    pub is_long_term: ::std::os::raw::c_int,
    pub not_existing: ::std::os::raw::c_int,
    pub used_for_reference: ::std::os::raw::c_int,
    pub FieldOrderCnt: [::std::os::raw::c_int; 2usize],
}
pub type CUVIDH264DPBENTRY = _CUVIDH264DPBENTRY;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDH264MVCEXT {
    pub num_views_minus1: ::std::os::raw::c_int,
    pub view_id: ::std::os::raw::c_int,
    pub inter_view_flag: ::std::os::raw::c_uchar,
    pub num_inter_view_refs_l0: ::std::os::raw::c_uchar,
    pub num_inter_view_refs_l1: ::std::os::raw::c_uchar,
    pub MVCReserved8Bits: ::std::os::raw::c_uchar,
    pub InterViewRefsL0: [::std::os::raw::c_int; 16usize],
    pub InterViewRefsL1: [::std::os::raw::c_int; 16usize],
}
pub type CUVIDH264MVCEXT = _CUVIDH264MVCEXT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _CUVIDH264SVCEXT {
    pub profile_idc: ::std::os::raw::c_uchar,
    pub level_idc: ::std::os::raw::c_uchar,
    pub DQId: ::std::os::raw::c_uchar,
    pub DQIdMax: ::std::os::raw::c_uchar,
    pub disable_inter_layer_deblocking_filter_idc: ::std::os::raw::c_uchar,
    pub ref_layer_chroma_phase_y_plus1: ::std::os::raw::c_uchar,
    pub inter_layer_slice_alpha_c0_offset_div2: ::std::os::raw::c_schar,
    pub inter_layer_slice_beta_offset_div2: ::std::os::raw::c_schar,
    pub DPBEntryValidFlag: ::std::os::raw::c_ushort,
    pub inter_layer_deblocking_filter_control_present_flag: ::std::os::raw::c_uchar,
    pub extended_spatial_scalability_idc: ::std::os::raw::c_uchar,
    pub adaptive_tcoeff_level_prediction_flag: ::std::os::raw::c_uchar,
    pub slice_header_restriction_flag: ::std::os::raw::c_uchar,
    pub chroma_phase_x_plus1_flag: ::std::os::raw::c_uchar,
    pub chroma_phase_y_plus1: ::std::os::raw::c_uchar,
    pub tcoeff_level_prediction_flag: ::std::os::raw::c_uchar,
    pub constrained_intra_resampling_flag: ::std::os::raw::c_uchar,
    pub ref_layer_chroma_phase_x_plus1_flag: ::std::os::raw::c_uchar,
    pub store_ref_base_pic_flag: ::std::os::raw::c_uchar,
    pub Reserved8BitsA: ::std::os::raw::c_uchar,
    pub Reserved8BitsB: ::std::os::raw::c_uchar,
    pub scaled_ref_layer_left_offset: ::std::os::raw::c_short,
    pub scaled_ref_layer_top_offset: ::std::os::raw::c_short,
    pub scaled_ref_layer_right_offset: ::std::os::raw::c_short,
    pub scaled_ref_layer_bottom_offset: ::std::os::raw::c_short,
    pub Reserved16Bits: ::std::os::raw::c_ushort,
    pub pNextLayer: *mut _CUVIDPICPARAMS,
    pub bRefBaseLayer: ::std::os::raw::c_int,
}
impl Default for _CUVIDH264SVCEXT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDH264SVCEXT = _CUVIDH264SVCEXT;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _CUVIDH264PICPARAMS {
    pub log2_max_frame_num_minus4: ::std::os::raw::c_int,
    pub pic_order_cnt_type: ::std::os::raw::c_int,
    pub log2_max_pic_order_cnt_lsb_minus4: ::std::os::raw::c_int,
    pub delta_pic_order_always_zero_flag: ::std::os::raw::c_int,
    pub frame_mbs_only_flag: ::std::os::raw::c_int,
    pub direct_8x8_inference_flag: ::std::os::raw::c_int,
    pub num_ref_frames: ::std::os::raw::c_int,
    pub residual_colour_transform_flag: ::std::os::raw::c_uchar,
    pub bit_depth_luma_minus8: ::std::os::raw::c_uchar,
    pub bit_depth_chroma_minus8: ::std::os::raw::c_uchar,
    pub qpprime_y_zero_transform_bypass_flag: ::std::os::raw::c_uchar,
    pub entropy_coding_mode_flag: ::std::os::raw::c_int,
    pub pic_order_present_flag: ::std::os::raw::c_int,
    pub num_ref_idx_l0_active_minus1: ::std::os::raw::c_int,
    pub num_ref_idx_l1_active_minus1: ::std::os::raw::c_int,
    pub weighted_pred_flag: ::std::os::raw::c_int,
    pub weighted_bipred_idc: ::std::os::raw::c_int,
    pub pic_init_qp_minus26: ::std::os::raw::c_int,
    pub deblocking_filter_control_present_flag: ::std::os::raw::c_int,
    pub redundant_pic_cnt_present_flag: ::std::os::raw::c_int,
    pub transform_8x8_mode_flag: ::std::os::raw::c_int,
    pub MbaffFrameFlag: ::std::os::raw::c_int,
    pub constrained_intra_pred_flag: ::std::os::raw::c_int,
    pub chroma_qp_index_offset: ::std::os::raw::c_int,
    pub second_chroma_qp_index_offset: ::std::os::raw::c_int,
    pub ref_pic_flag: ::std::os::raw::c_int,
    pub frame_num: ::std::os::raw::c_int,
    pub CurrFieldOrderCnt: [::std::os::raw::c_int; 2usize],
    pub dpb: [CUVIDH264DPBENTRY; 16usize],
    pub WeightScale4x4: [[::std::os::raw::c_uchar; 16usize]; 6usize],
    pub WeightScale8x8: [[::std::os::raw::c_uchar; 64usize]; 2usize],
    pub fmo_aso_enable: ::std::os::raw::c_uchar,
    pub num_slice_groups_minus1: ::std::os::raw::c_uchar,
    pub slice_group_map_type: ::std::os::raw::c_uchar,
    pub pic_init_qs_minus26: ::std::os::raw::c_schar,
    pub slice_group_change_rate_minus1: ::std::os::raw::c_uint,
    pub fmo: _CUVIDH264PICPARAMS__bindgen_ty_1,
    pub Reserved: [::std::os::raw::c_uint; 12usize],
    pub __bindgen_anon_1: _CUVIDH264PICPARAMS__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _CUVIDH264PICPARAMS__bindgen_ty_1 {
    pub slice_group_map_addr: ::std::os::raw::c_ulonglong,
    pub pMb2SliceGroupMap: *const ::std::os::raw::c_uchar,
}
impl Default for _CUVIDH264PICPARAMS__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _CUVIDH264PICPARAMS__bindgen_ty_2 {
    pub mvcext: CUVIDH264MVCEXT,
    pub svcext: CUVIDH264SVCEXT,
}
impl Default for _CUVIDH264PICPARAMS__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _CUVIDH264PICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDH264PICPARAMS = _CUVIDH264PICPARAMS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _CUVIDMPEG2PICPARAMS {
    pub ForwardRefIdx: ::std::os::raw::c_int,
    pub BackwardRefIdx: ::std::os::raw::c_int,
    pub picture_coding_type: ::std::os::raw::c_int,
    pub full_pel_forward_vector: ::std::os::raw::c_int,
    pub full_pel_backward_vector: ::std::os::raw::c_int,
    pub f_code: [[::std::os::raw::c_int; 2usize]; 2usize],
    pub intra_dc_precision: ::std::os::raw::c_int,
    pub frame_pred_frame_dct: ::std::os::raw::c_int,
    pub concealment_motion_vectors: ::std::os::raw::c_int,
    pub q_scale_type: ::std::os::raw::c_int,
    pub intra_vlc_format: ::std::os::raw::c_int,
    pub alternate_scan: ::std::os::raw::c_int,
    pub top_field_first: ::std::os::raw::c_int,
    pub QuantMatrixIntra: [::std::os::raw::c_uchar; 64usize],
    pub QuantMatrixInter: [::std::os::raw::c_uchar; 64usize],
}
impl Default for _CUVIDMPEG2PICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDMPEG2PICPARAMS = _CUVIDMPEG2PICPARAMS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _CUVIDMPEG4PICPARAMS {
    pub ForwardRefIdx: ::std::os::raw::c_int,
    pub BackwardRefIdx: ::std::os::raw::c_int,
    pub video_object_layer_width: ::std::os::raw::c_int,
    pub video_object_layer_height: ::std::os::raw::c_int,
    pub vop_time_increment_bitcount: ::std::os::raw::c_int,
    pub top_field_first: ::std::os::raw::c_int,
    pub resync_marker_disable: ::std::os::raw::c_int,
    pub quant_type: ::std::os::raw::c_int,
    pub quarter_sample: ::std::os::raw::c_int,
    pub short_video_header: ::std::os::raw::c_int,
    pub divx_flags: ::std::os::raw::c_int,
    pub vop_coding_type: ::std::os::raw::c_int,
    pub vop_coded: ::std::os::raw::c_int,
    pub vop_rounding_type: ::std::os::raw::c_int,
    pub alternate_vertical_scan_flag: ::std::os::raw::c_int,
    pub interlaced: ::std::os::raw::c_int,
    pub vop_fcode_forward: ::std::os::raw::c_int,
    pub vop_fcode_backward: ::std::os::raw::c_int,
    pub trd: [::std::os::raw::c_int; 2usize],
    pub trb: [::std::os::raw::c_int; 2usize],
    pub QuantMatrixIntra: [::std::os::raw::c_uchar; 64usize],
    pub QuantMatrixInter: [::std::os::raw::c_uchar; 64usize],
    pub gmc_enabled: ::std::os::raw::c_int,
}
impl Default for _CUVIDMPEG4PICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDMPEG4PICPARAMS = _CUVIDMPEG4PICPARAMS;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDVC1PICPARAMS {
    pub ForwardRefIdx: ::std::os::raw::c_int,
    pub BackwardRefIdx: ::std::os::raw::c_int,
    pub FrameWidth: ::std::os::raw::c_int,
    pub FrameHeight: ::std::os::raw::c_int,
    pub intra_pic_flag: ::std::os::raw::c_int,
    pub ref_pic_flag: ::std::os::raw::c_int,
    pub progressive_fcm: ::std::os::raw::c_int,
    pub profile: ::std::os::raw::c_int,
    pub postprocflag: ::std::os::raw::c_int,
    pub pulldown: ::std::os::raw::c_int,
    pub interlace: ::std::os::raw::c_int,
    pub tfcntrflag: ::std::os::raw::c_int,
    pub finterpflag: ::std::os::raw::c_int,
    pub psf: ::std::os::raw::c_int,
    pub multires: ::std::os::raw::c_int,
    pub syncmarker: ::std::os::raw::c_int,
    pub rangered: ::std::os::raw::c_int,
    pub maxbframes: ::std::os::raw::c_int,
    pub panscan_flag: ::std::os::raw::c_int,
    pub refdist_flag: ::std::os::raw::c_int,
    pub extended_mv: ::std::os::raw::c_int,
    pub dquant: ::std::os::raw::c_int,
    pub vstransform: ::std::os::raw::c_int,
    pub loopfilter: ::std::os::raw::c_int,
    pub fastuvmc: ::std::os::raw::c_int,
    pub overlap: ::std::os::raw::c_int,
    pub quantizer: ::std::os::raw::c_int,
    pub extended_dmv: ::std::os::raw::c_int,
    pub range_mapy_flag: ::std::os::raw::c_int,
    pub range_mapy: ::std::os::raw::c_int,
    pub range_mapuv_flag: ::std::os::raw::c_int,
    pub range_mapuv: ::std::os::raw::c_int,
    pub rangeredfrm: ::std::os::raw::c_int,
}
pub type CUVIDVC1PICPARAMS = _CUVIDVC1PICPARAMS;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDJPEGPICPARAMS {
    pub Reserved: ::std::os::raw::c_int,
}
pub type CUVIDJPEGPICPARAMS = _CUVIDJPEGPICPARAMS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _CUVIDHEVCPICPARAMS {
    pub pic_width_in_luma_samples: ::std::os::raw::c_int,
    pub pic_height_in_luma_samples: ::std::os::raw::c_int,
    pub log2_min_luma_coding_block_size_minus3: ::std::os::raw::c_uchar,
    pub log2_diff_max_min_luma_coding_block_size: ::std::os::raw::c_uchar,
    pub log2_min_transform_block_size_minus2: ::std::os::raw::c_uchar,
    pub log2_diff_max_min_transform_block_size: ::std::os::raw::c_uchar,
    pub pcm_enabled_flag: ::std::os::raw::c_uchar,
    pub log2_min_pcm_luma_coding_block_size_minus3: ::std::os::raw::c_uchar,
    pub log2_diff_max_min_pcm_luma_coding_block_size: ::std::os::raw::c_uchar,
    pub pcm_sample_bit_depth_luma_minus1: ::std::os::raw::c_uchar,
    pub pcm_sample_bit_depth_chroma_minus1: ::std::os::raw::c_uchar,
    pub pcm_loop_filter_disabled_flag: ::std::os::raw::c_uchar,
    pub strong_intra_smoothing_enabled_flag: ::std::os::raw::c_uchar,
    pub max_transform_hierarchy_depth_intra: ::std::os::raw::c_uchar,
    pub max_transform_hierarchy_depth_inter: ::std::os::raw::c_uchar,
    pub amp_enabled_flag: ::std::os::raw::c_uchar,
    pub separate_colour_plane_flag: ::std::os::raw::c_uchar,
    pub log2_max_pic_order_cnt_lsb_minus4: ::std::os::raw::c_uchar,
    pub num_short_term_ref_pic_sets: ::std::os::raw::c_uchar,
    pub long_term_ref_pics_present_flag: ::std::os::raw::c_uchar,
    pub num_long_term_ref_pics_sps: ::std::os::raw::c_uchar,
    pub sps_temporal_mvp_enabled_flag: ::std::os::raw::c_uchar,
    pub sample_adaptive_offset_enabled_flag: ::std::os::raw::c_uchar,
    pub scaling_list_enable_flag: ::std::os::raw::c_uchar,
    pub IrapPicFlag: ::std::os::raw::c_uchar,
    pub IdrPicFlag: ::std::os::raw::c_uchar,
    pub bit_depth_luma_minus8: ::std::os::raw::c_uchar,
    pub bit_depth_chroma_minus8: ::std::os::raw::c_uchar,
    pub log2_max_transform_skip_block_size_minus2: ::std::os::raw::c_uchar,
    pub log2_sao_offset_scale_luma: ::std::os::raw::c_uchar,
    pub log2_sao_offset_scale_chroma: ::std::os::raw::c_uchar,
    pub high_precision_offsets_enabled_flag: ::std::os::raw::c_uchar,
    pub reserved1: [::std::os::raw::c_uchar; 10usize],
    pub dependent_slice_segments_enabled_flag: ::std::os::raw::c_uchar,
    pub slice_segment_header_extension_present_flag: ::std::os::raw::c_uchar,
    pub sign_data_hiding_enabled_flag: ::std::os::raw::c_uchar,
    pub cu_qp_delta_enabled_flag: ::std::os::raw::c_uchar,
    pub diff_cu_qp_delta_depth: ::std::os::raw::c_uchar,
    pub init_qp_minus26: ::std::os::raw::c_schar,
    pub pps_cb_qp_offset: ::std::os::raw::c_schar,
    pub pps_cr_qp_offset: ::std::os::raw::c_schar,
    pub constrained_intra_pred_flag: ::std::os::raw::c_uchar,
    pub weighted_pred_flag: ::std::os::raw::c_uchar,
    pub weighted_bipred_flag: ::std::os::raw::c_uchar,
    pub transform_skip_enabled_flag: ::std::os::raw::c_uchar,
    pub transquant_bypass_enabled_flag: ::std::os::raw::c_uchar,
    pub entropy_coding_sync_enabled_flag: ::std::os::raw::c_uchar,
    pub log2_parallel_merge_level_minus2: ::std::os::raw::c_uchar,
    pub num_extra_slice_header_bits: ::std::os::raw::c_uchar,
    pub loop_filter_across_tiles_enabled_flag: ::std::os::raw::c_uchar,
    pub loop_filter_across_slices_enabled_flag: ::std::os::raw::c_uchar,
    pub output_flag_present_flag: ::std::os::raw::c_uchar,
    pub num_ref_idx_l0_default_active_minus1: ::std::os::raw::c_uchar,
    pub num_ref_idx_l1_default_active_minus1: ::std::os::raw::c_uchar,
    pub lists_modification_present_flag: ::std::os::raw::c_uchar,
    pub cabac_init_present_flag: ::std::os::raw::c_uchar,
    pub pps_slice_chroma_qp_offsets_present_flag: ::std::os::raw::c_uchar,
    pub deblocking_filter_override_enabled_flag: ::std::os::raw::c_uchar,
    pub pps_deblocking_filter_disabled_flag: ::std::os::raw::c_uchar,
    pub pps_beta_offset_div2: ::std::os::raw::c_schar,
    pub pps_tc_offset_div2: ::std::os::raw::c_schar,
    pub tiles_enabled_flag: ::std::os::raw::c_uchar,
    pub uniform_spacing_flag: ::std::os::raw::c_uchar,
    pub num_tile_columns_minus1: ::std::os::raw::c_uchar,
    pub num_tile_rows_minus1: ::std::os::raw::c_uchar,
    pub column_width_minus1: [::std::os::raw::c_ushort; 21usize],
    pub row_height_minus1: [::std::os::raw::c_ushort; 21usize],
    pub reserved3: [::std::os::raw::c_uint; 15usize],
    pub NumBitsForShortTermRPSInSlice: ::std::os::raw::c_int,
    pub NumDeltaPocsOfRefRpsIdx: ::std::os::raw::c_int,
    pub NumPocTotalCurr: ::std::os::raw::c_int,
    pub NumPocStCurrBefore: ::std::os::raw::c_int,
    pub NumPocStCurrAfter: ::std::os::raw::c_int,
    pub NumPocLtCurr: ::std::os::raw::c_int,
    pub CurrPicOrderCntVal: ::std::os::raw::c_int,
    pub RefPicIdx: [::std::os::raw::c_int; 16usize],
    pub PicOrderCntVal: [::std::os::raw::c_int; 16usize],
    pub IsLongTerm: [::std::os::raw::c_uchar; 16usize],
    pub RefPicSetStCurrBefore: [::std::os::raw::c_uchar; 8usize],
    pub RefPicSetStCurrAfter: [::std::os::raw::c_uchar; 8usize],
    pub RefPicSetLtCurr: [::std::os::raw::c_uchar; 8usize],
    pub RefPicSetInterLayer0: [::std::os::raw::c_uchar; 8usize],
    pub RefPicSetInterLayer1: [::std::os::raw::c_uchar; 8usize],
    pub reserved4: [::std::os::raw::c_uint; 12usize],
    pub ScalingList4x4: [[::std::os::raw::c_uchar; 16usize]; 6usize],
    pub ScalingList8x8: [[::std::os::raw::c_uchar; 64usize]; 6usize],
    pub ScalingList16x16: [[::std::os::raw::c_uchar; 64usize]; 6usize],
    pub ScalingList32x32: [[::std::os::raw::c_uchar; 64usize]; 2usize],
    pub ScalingListDCCoeff16x16: [::std::os::raw::c_uchar; 6usize],
    pub ScalingListDCCoeff32x32: [::std::os::raw::c_uchar; 2usize],
}
impl Default for _CUVIDHEVCPICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDHEVCPICPARAMS = _CUVIDHEVCPICPARAMS;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _CUVIDVP8PICPARAMS {
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub first_partition_size: ::std::os::raw::c_uint,
    pub LastRefIdx: ::std::os::raw::c_uchar,
    pub GoldenRefIdx: ::std::os::raw::c_uchar,
    pub AltRefIdx: ::std::os::raw::c_uchar,
    pub __bindgen_anon_1: _CUVIDVP8PICPARAMS__bindgen_ty_1,
    pub Reserved1: [::std::os::raw::c_uchar; 4usize],
    pub Reserved2: [::std::os::raw::c_uint; 3usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _CUVIDVP8PICPARAMS__bindgen_ty_1 {
    pub vp8_frame_tag: _CUVIDVP8PICPARAMS__bindgen_ty_1__bindgen_ty_1,
    pub wFrameTagFlags: ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDVP8PICPARAMS__bindgen_ty_1__bindgen_ty_1 {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
}
impl _CUVIDVP8PICPARAMS__bindgen_ty_1__bindgen_ty_1 {
    #[inline]
    pub fn frame_type(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_frame_type(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn frame_type_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_frame_type_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn version(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 3u8) as u8) }
    }
    #[inline]
    pub fn set_version(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn version_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                1usize,
                3u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_version_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                1usize,
                3u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn show_frame(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_show_frame(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn show_frame_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                4usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_show_frame_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                4usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn update_mb_segmentation_data(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_update_mb_segmentation_data(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn update_mb_segmentation_data_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                5usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_update_mb_segmentation_data_raw(
        this: *mut Self,
        val: ::std::os::raw::c_uchar,
    ) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                5usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn Reserved2Bits(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 2u8) as u8) }
    }
    #[inline]
    pub fn set_Reserved2Bits(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn Reserved2Bits_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                6usize,
                2u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_Reserved2Bits_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                6usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        frame_type: ::std::os::raw::c_uchar,
        version: ::std::os::raw::c_uchar,
        show_frame: ::std::os::raw::c_uchar,
        update_mb_segmentation_data: ::std::os::raw::c_uchar,
        Reserved2Bits: ::std::os::raw::c_uchar,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let frame_type: u8 = unsafe { ::std::mem::transmute(frame_type) };
            frame_type as u64
        });
        __bindgen_bitfield_unit.set(1usize, 3u8, {
            let version: u8 = unsafe { ::std::mem::transmute(version) };
            version as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let show_frame: u8 = unsafe { ::std::mem::transmute(show_frame) };
            show_frame as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let update_mb_segmentation_data: u8 =
                unsafe { ::std::mem::transmute(update_mb_segmentation_data) };
            update_mb_segmentation_data as u64
        });
        __bindgen_bitfield_unit.set(6usize, 2u8, {
            let Reserved2Bits: u8 = unsafe { ::std::mem::transmute(Reserved2Bits) };
            Reserved2Bits as u64
        });
        __bindgen_bitfield_unit
    }
}
impl Default for _CUVIDVP8PICPARAMS__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _CUVIDVP8PICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDVP8PICPARAMS = _CUVIDVP8PICPARAMS;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CUVIDVP9PICPARAMS {
    pub width: ::std::os::raw::c_uint,
    pub height: ::std::os::raw::c_uint,
    pub LastRefIdx: ::std::os::raw::c_uchar,
    pub GoldenRefIdx: ::std::os::raw::c_uchar,
    pub AltRefIdx: ::std::os::raw::c_uchar,
    pub colorSpace: ::std::os::raw::c_uchar,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
    pub reserved16Bits: ::std::os::raw::c_ushort,
    pub refFrameSignBias: [::std::os::raw::c_uchar; 4usize],
    pub bitDepthMinus8Luma: ::std::os::raw::c_uchar,
    pub bitDepthMinus8Chroma: ::std::os::raw::c_uchar,
    pub loopFilterLevel: ::std::os::raw::c_uchar,
    pub loopFilterSharpness: ::std::os::raw::c_uchar,
    pub modeRefLfEnabled: ::std::os::raw::c_uchar,
    pub log2_tile_columns: ::std::os::raw::c_uchar,
    pub log2_tile_rows: ::std::os::raw::c_uchar,
    pub _bitfield_align_2: [u8; 0],
    pub _bitfield_2: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub segmentFeatureEnable: [[::std::os::raw::c_uchar; 4usize]; 8usize],
    pub segmentFeatureData: [[::std::os::raw::c_short; 4usize]; 8usize],
    pub mb_segment_tree_probs: [::std::os::raw::c_uchar; 7usize],
    pub segment_pred_probs: [::std::os::raw::c_uchar; 3usize],
    pub reservedSegment16Bits: [::std::os::raw::c_uchar; 2usize],
    pub qpYAc: ::std::os::raw::c_int,
    pub qpYDc: ::std::os::raw::c_int,
    pub qpChDc: ::std::os::raw::c_int,
    pub qpChAc: ::std::os::raw::c_int,
    pub activeRefIdx: [::std::os::raw::c_uint; 3usize],
    pub resetFrameContext: ::std::os::raw::c_uint,
    pub mcomp_filter_type: ::std::os::raw::c_uint,
    pub mbRefLfDelta: [::std::os::raw::c_uint; 4usize],
    pub mbModeLfDelta: [::std::os::raw::c_uint; 2usize],
    pub frameTagSize: ::std::os::raw::c_uint,
    pub offsetToDctParts: ::std::os::raw::c_uint,
    pub reserved128Bits: [::std::os::raw::c_uint; 4usize],
}
impl _CUVIDVP9PICPARAMS {
    #[inline]
    pub fn profile(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 3u8) as u16) }
    }
    #[inline]
    pub fn set_profile(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn profile_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                3u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_profile_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                3u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn frameContextIdx(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 2u8) as u16) }
    }
    #[inline]
    pub fn set_frameContextIdx(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn frameContextIdx_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                3usize,
                2u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_frameContextIdx_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                3usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn frameType(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_frameType(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn frameType_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                5usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_frameType_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                5usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn showFrame(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_showFrame(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn showFrame_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                6usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_showFrame_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                6usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn errorResilient(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(7usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_errorResilient(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(7usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn errorResilient_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                7usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_errorResilient_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                7usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn frameParallelDecoding(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(8usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_frameParallelDecoding(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(8usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn frameParallelDecoding_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                8usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_frameParallelDecoding_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                8usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn subSamplingX(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(9usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_subSamplingX(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(9usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn subSamplingX_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                9usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_subSamplingX_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                9usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn subSamplingY(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(10usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_subSamplingY(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(10usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn subSamplingY_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                10usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_subSamplingY_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                10usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn intraOnly(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(11usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_intraOnly(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(11usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn intraOnly_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                11usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_intraOnly_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                11usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn allow_high_precision_mv(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(12usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_allow_high_precision_mv(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(12usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn allow_high_precision_mv_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                12usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_allow_high_precision_mv_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                12usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn refreshEntropyProbs(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(13usize, 1u8) as u16) }
    }
    #[inline]
    pub fn set_refreshEntropyProbs(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(13usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn refreshEntropyProbs_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                13usize,
                1u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_refreshEntropyProbs_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                13usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn reserved2Bits(&self) -> ::std::os::raw::c_ushort {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(14usize, 2u8) as u16) }
    }
    #[inline]
    pub fn set_reserved2Bits(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set(14usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn reserved2Bits_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 2usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                14usize,
                2u8,
            ) as u16)
        }
    }
    #[inline]
    pub unsafe fn set_reserved2Bits_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 2usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                14usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        profile: ::std::os::raw::c_ushort,
        frameContextIdx: ::std::os::raw::c_ushort,
        frameType: ::std::os::raw::c_ushort,
        showFrame: ::std::os::raw::c_ushort,
        errorResilient: ::std::os::raw::c_ushort,
        frameParallelDecoding: ::std::os::raw::c_ushort,
        subSamplingX: ::std::os::raw::c_ushort,
        subSamplingY: ::std::os::raw::c_ushort,
        intraOnly: ::std::os::raw::c_ushort,
        allow_high_precision_mv: ::std::os::raw::c_ushort,
        refreshEntropyProbs: ::std::os::raw::c_ushort,
        reserved2Bits: ::std::os::raw::c_ushort,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 3u8, {
            let profile: u16 = unsafe { ::std::mem::transmute(profile) };
            profile as u64
        });
        __bindgen_bitfield_unit.set(3usize, 2u8, {
            let frameContextIdx: u16 = unsafe { ::std::mem::transmute(frameContextIdx) };
            frameContextIdx as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let frameType: u16 = unsafe { ::std::mem::transmute(frameType) };
            frameType as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let showFrame: u16 = unsafe { ::std::mem::transmute(showFrame) };
            showFrame as u64
        });
        __bindgen_bitfield_unit.set(7usize, 1u8, {
            let errorResilient: u16 = unsafe { ::std::mem::transmute(errorResilient) };
            errorResilient as u64
        });
        __bindgen_bitfield_unit.set(8usize, 1u8, {
            let frameParallelDecoding: u16 =
                unsafe { ::std::mem::transmute(frameParallelDecoding) };
            frameParallelDecoding as u64
        });
        __bindgen_bitfield_unit.set(9usize, 1u8, {
            let subSamplingX: u16 = unsafe { ::std::mem::transmute(subSamplingX) };
            subSamplingX as u64
        });
        __bindgen_bitfield_unit.set(10usize, 1u8, {
            let subSamplingY: u16 = unsafe { ::std::mem::transmute(subSamplingY) };
            subSamplingY as u64
        });
        __bindgen_bitfield_unit.set(11usize, 1u8, {
            let intraOnly: u16 = unsafe { ::std::mem::transmute(intraOnly) };
            intraOnly as u64
        });
        __bindgen_bitfield_unit.set(12usize, 1u8, {
            let allow_high_precision_mv: u16 =
                unsafe { ::std::mem::transmute(allow_high_precision_mv) };
            allow_high_precision_mv as u64
        });
        __bindgen_bitfield_unit.set(13usize, 1u8, {
            let refreshEntropyProbs: u16 = unsafe { ::std::mem::transmute(refreshEntropyProbs) };
            refreshEntropyProbs as u64
        });
        __bindgen_bitfield_unit.set(14usize, 2u8, {
            let reserved2Bits: u16 = unsafe { ::std::mem::transmute(reserved2Bits) };
            reserved2Bits as u64
        });
        __bindgen_bitfield_unit
    }
    #[inline]
    pub fn segmentEnabled(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_2.get(0usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_segmentEnabled(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_2.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn segmentEnabled_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_2),
                0usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_segmentEnabled_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_2),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn segmentMapUpdate(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_2.get(1usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_segmentMapUpdate(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_2.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn segmentMapUpdate_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_2),
                1usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_segmentMapUpdate_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_2),
                1usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn segmentMapTemporalUpdate(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_2.get(2usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_segmentMapTemporalUpdate(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_2.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn segmentMapTemporalUpdate_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_2),
                2usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_segmentMapTemporalUpdate_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_2),
                2usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn segmentFeatureMode(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_2.get(3usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_segmentFeatureMode(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_2.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn segmentFeatureMode_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_2),
                3usize,
                1u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_segmentFeatureMode_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_2),
                3usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn reserved4Bits(&self) -> ::std::os::raw::c_uchar {
        unsafe { ::std::mem::transmute(self._bitfield_2.get(4usize, 4u8) as u8) }
    }
    #[inline]
    pub fn set_reserved4Bits(&mut self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_2.set(4usize, 4u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn reserved4Bits_raw(this: *const Self) -> ::std::os::raw::c_uchar {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_2),
                4usize,
                4u8,
            ) as u8)
        }
    }
    #[inline]
    pub unsafe fn set_reserved4Bits_raw(this: *mut Self, val: ::std::os::raw::c_uchar) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_2),
                4usize,
                4u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_2(
        segmentEnabled: ::std::os::raw::c_uchar,
        segmentMapUpdate: ::std::os::raw::c_uchar,
        segmentMapTemporalUpdate: ::std::os::raw::c_uchar,
        segmentFeatureMode: ::std::os::raw::c_uchar,
        reserved4Bits: ::std::os::raw::c_uchar,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let segmentEnabled: u8 = unsafe { ::std::mem::transmute(segmentEnabled) };
            segmentEnabled as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let segmentMapUpdate: u8 = unsafe { ::std::mem::transmute(segmentMapUpdate) };
            segmentMapUpdate as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let segmentMapTemporalUpdate: u8 =
                unsafe { ::std::mem::transmute(segmentMapTemporalUpdate) };
            segmentMapTemporalUpdate as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let segmentFeatureMode: u8 = unsafe { ::std::mem::transmute(segmentFeatureMode) };
            segmentFeatureMode as u64
        });
        __bindgen_bitfield_unit.set(4usize, 4u8, {
            let reserved4Bits: u8 = unsafe { ::std::mem::transmute(reserved4Bits) };
            reserved4Bits as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type CUVIDVP9PICPARAMS = _CUVIDVP9PICPARAMS;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _CUVIDPICPARAMS {
    pub PicWidthInMbs: ::std::os::raw::c_int,
    pub FrameHeightInMbs: ::std::os::raw::c_int,
    pub CurrPicIdx: ::std::os::raw::c_int,
    pub field_pic_flag: ::std::os::raw::c_int,
    pub bottom_field_flag: ::std::os::raw::c_int,
    pub second_field: ::std::os::raw::c_int,
    pub nBitstreamDataLen: ::std::os::raw::c_uint,
    pub pBitstreamData: *const ::std::os::raw::c_uchar,
    pub nNumSlices: ::std::os::raw::c_uint,
    pub pSliceDataOffsets: *const ::std::os::raw::c_uint,
    pub ref_pic_flag: ::std::os::raw::c_int,
    pub intra_pic_flag: ::std::os::raw::c_int,
    pub Reserved: [::std::os::raw::c_uint; 30usize],
    pub CodecSpecific: _CUVIDPICPARAMS__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _CUVIDPICPARAMS__bindgen_ty_1 {
    pub mpeg2: CUVIDMPEG2PICPARAMS,
    pub h264: CUVIDH264PICPARAMS,
    pub vc1: CUVIDVC1PICPARAMS,
    pub mpeg4: CUVIDMPEG4PICPARAMS,
    pub jpeg: CUVIDJPEGPICPARAMS,
    pub hevc: CUVIDHEVCPICPARAMS,
    pub vp8: CUVIDVP8PICPARAMS,
    pub vp9: CUVIDVP9PICPARAMS,
    pub CodecReserved: [::std::os::raw::c_uint; 1024usize],
}
impl Default for _CUVIDPICPARAMS__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _CUVIDPICPARAMS {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUVIDPICPARAMS = _CUVIDPICPARAMS;
