//! Normative AV1 quantizer weights; generated by generate_av1_quant_matrix_tables.py.
//! Source SHA-256: 9d9a54994541adbd61e83f9af95aad818ea8e5608d090a9553d2178bbef52998
//! Data SHA-256: faa3960fa4f18495e3b627a7b75bfe22959979894fab1aa37aa8a52faba1c323
const WEIGHTS: &[u8; 100320] = include_bytes!("av1_quant_matrix.bin");
const OFFSETS: [usize; 19] = [
    0, 16, 80, 336, 336, 1360, 1392, 1424, 1552, 1680, 2192, 336, 336, 2704, 2768, 2832, 3088,
    1680, 2192,
];
const SHAPES: [[usize; 2]; 19] = [
    [4, 4],
    [8, 8],
    [16, 16],
    [32, 32],
    [64, 64],
    [4, 8],
    [8, 4],
    [8, 16],
    [16, 8],
    [16, 32],
    [32, 16],
    [32, 64],
    [64, 32],
    [4, 16],
    [16, 4],
    [8, 32],
    [32, 8],
    [16, 64],
    [64, 16],
];
/// Coefficients and transform dimensions have already been validated by the caller.
pub(super) fn weights(level: u8, chroma: bool, size: [usize; 2]) -> &'static [u8] {
    let index = SHAPES
        .iter()
        .position(|s| *s == size)
        .expect("validated AV1 transform");
    let offset = (usize::from(level) * 2 + usize::from(chroma)) * 3344 + OFFSETS[index];
    let length = size[0].min(32) * size[1].min(32);
    &WEIGHTS[offset..offset + length]
}
