//! Extract templates only from owned files generated by scripts/av1_fixture.c.
use fvid_codecs::codec::{av1::Obus, av1_frame::Header, av1_sequence::Sequence};
fn main() {
    println!(
        "{{\"source\":\"scripts/av1_fixture.c, 32 1 QUANTIZER 0 4 8 0 0 1 1; second key and first inter tiles\",\"templates\":["
    );
    let mut comma = false;
    for path in std::env::args().skip(1) {
        let data = std::fs::read(path).unwrap();
        let mut sequence = None;
        let mut refs: [Option<Header>; 8] = std::array::from_fn(|_| None);
        let mut frames = Vec::new();
        for obu in Obus::new(&data) {
            let obu = obu.unwrap();
            if obu.kind == 1 {
                let s = Sequence::parse(obu.payload).unwrap();
                assert_eq!(s.max_size, [32, 32]);
                assert_eq!(s.color.depth, 8);
                assert_eq!(s.order_hint_bits, 0);
                sequence = Some(s);
            }
            if obu.kind == 6 {
                let h = Header::parse(
                    sequence.as_ref().unwrap(),
                    obu.payload,
                    0,
                    0,
                    &std::array::from_fn(|i| refs[i].as_ref()),
                )
                .unwrap();
                for i in 0..8 {
                    if h.refresh_flags & (1 << i) != 0 {
                        refs[i] = Some(h.clone());
                    }
                }
                let tile = obu.payload[h.header_bytes..].to_vec();
                frames.push((h, tile));
            }
        }
        let (key, key_tile) = &frames[1];
        let (inter, inter_tile) = &frames[2];
        assert_eq!(key.frame_type, 0);
        assert_eq!(inter.frame_type, 1);
        for h in [key, inter] {
            assert!(h.disable_cdf_update);
            assert!(!h.screen_content);
            assert!(!h.reference_select);
            assert_eq!(h.quant.delta, [0; 5]);
            assert_eq!(h.filter.levels, [0; 4]);
            assert_eq!(h.primary_reference, 7);
        }
        assert_eq!(key.quant.base, inter.quant.base);
        assert_eq!(inter.references, [0; 7]);
        assert_eq!(inter.interpolation_filter, 0);
        if comma {
            println!(",");
        }
        comma = true;
        println!(
            "{{\"qindex\":{},\"key_tx_mode\":{},\"inter_tx_mode\":{},\"high_precision_mv\":{},\"key_tile\":{:?},\"inter_tile\":{:?}}}",
            key.quant.base,
            key.tx_mode,
            inter.tx_mode,
            inter.high_precision_mv,
            key_tile,
            inter_tile
        );
    }
    println!("]}}");
}
