#!/usr/bin/env python3
"""Extract H.264 arithmetic tables from the pinned official ITU PDF.
Requires pypdf and pdfplumber only for regeneration; no decoder dependency.
"""
import hashlib
from pathlib import Path
import re
import sys
from pypdf import PdfReader

source = Path(sys.argv[1])
assert hashlib.sha256(source.read_bytes()).hexdigest() == '1a73f86fd39fb00e2b15dc543c1a18f8f49c012dd76876f16b3669f0ae6d9ab2'
reader = PdfReader(source)
ranges = [None] * 64
for line in reader.pages[298].extract_text().splitlines():
    values = line.split()
    if len(values) == 10 and all(v.isdecimal() for v in values):
        values = list(map(int, values))
        for i in (0, 5):
            index = values[i]
            assert ranges[index] is None
            ranges[index] = values[i+1:i+5]
assert all(ranges)
lps, mps = [], []
for line in reader.pages[299].extract_text().splitlines():
    for name, target in [('transIdxLPS', lps), ('transIdxMPS', mps)]:
        if line.startswith(name):
            target.extend(map(int, re.findall(r'\d+', line)))
assert len(lps) == len(mps) == 64
assert all(0 <= v < 64 for v in lps + mps)
output = Path(__file__).resolve().parents[1] / 'src/codec/cabac_tables.rs'
with output.open('w') as out:
    out.write('// Generated by scripts/generate_cabac_tables.py from ITU-T H.264 (02/2016), tables 9-44 and 9-45.\n')
    out.write('pub(super) const RANGE_LPS: [[u16; 4]; 64] = [\n')
    for row in ranges:
        out.write(f'    {row},\n')
    out.write('];\n')
    out.write(f'pub(super) const TRANS_LPS: [u8; 64] = {lps};\n')
    out.write(f'pub(super) const TRANS_MPS: [u8; 64] = {mps};\n')

# Tables 9-12..9-24: base H.264 contexts (4:2:0/4:2:2, including 8x8).
# The early transposed tables wrap some negative integers across lines.
import pdfplumber
initial = [[None] * 460 for _ in range(4)]  # I, then cabac_init_idc 0/1/2

def number(cell):
    return int(''.join(cell.split()).replace('−', '-'))

def assign(group, index, pair):
    assert initial[group][index] is None, (group, index)
    assert all(-128 <= value <= 127 for value in pair)
    initial[group][index] = pair

with pdfplumber.open(source) as pdf:
    for page in (251, 252, 253):
        for table in pdf.pages[page].extract_tables():
            if 'ctxIdx' not in table[0]:
                continue
            start = table[0].index('ctxIdx')
            indices = list(map(number, table[1][start:]))
            for row in range(2, len(table), 2):
                ms, ns = table[row], table[row+1]
                groups = range(4) if start == 1 else [0 if ms[0] == 'I slices' else number(ms[0])+1]
                for index, m, n in zip(indices, ms[start:], ns[start:]):
                    if m != 'na':
                        for group in groups:
                            assign(group, index, (number(m), number(n)))
for page in range(254, 261):
    for line in reader.pages[page].extract_text().splitlines():
        values = line.replace('−', '-').split()
        if len(values) in (9, 18) and all(re.fullmatch(r'-?\d+', v) for v in values):
            values = list(map(int, values))
            for start in range(0, len(values), 9):
                index = values[start]
                assert 70 <= index < 460
                for group in range(4):
                    assign(group, index, tuple(values[start+1+group*2:start+3+group*2]))
for group in range(4):
    missing = {i for i, value in enumerate(initial[group]) if value is None}
    assert missing == ({276} | (set(range(11,60)) if group == 0 else set())), (group, missing)
output = output.with_name('avc_cabac_init.rs')
with output.open('w') as out:
    out.write('// Generated from ITU-T H.264 (02/2016), tables 9-12..9-24.\n')
    out.write('// None denotes an unused or termination context, never a default probability.\n')
    out.write('pub(super) const INIT: [[Option<(i8, i8)>; 460]; 4] = [\n')
    for group in initial:
        out.write('    [\n')
        for value in group:
            out.write('        '+('None' if value is None else f'Some(({value[0]}, {value[1]}))')+',\n')
        out.write('    ],\n')
    out.write('];\n')

scan = {'zig-zag': [], 'field': []}
for line in reader.pages[204].extract_text().splitlines():
    for name, values in scan.items():
        if line.startswith(name+' '):
            values.extend(int(row)*8+int(col) for row,col in re.findall(r'c([0-7])([0-7])',line))
assert all(sorted(values) == list(range(64)) for values in scan.values())
significance = [None]*63
for page in (293,294):
    for line in reader.pages[page].extract_text().splitlines():
        values=line.split()
        if len(values) in (4,8) and all(v.isdecimal() for v in values):
            values=list(map(int,values))
            for start in range(0,len(values),4):
                index=values[start]
                assert significance[index] is None
                significance[index]=values[start+1:start+4]
assert all(significance)
output=output.with_name('avc_8x8_tables.rs')
with output.open('w') as out:
    out.write('// Generated from ITU-T H.264 (02/2016), tables 8-14 and 9-43.\n')
    out.write(f'pub const FRAME_SCAN: [usize;64] = {scan["zig-zag"]};\n')
    out.write(f'pub const FIELD_SCAN: [usize;64] = {scan["field"]};\n')
    out.write('pub(super) const SIGNIFICANCE: [[usize;3];63] = [\n')
    for row in significance: out.write(f'    {row},\n')
    out.write('];\n')
