#!/usr/bin/env python3
"""Extract numeric normative AV1 tables from locally downloaded spec sections.
Usage: python3 scripts/generate_av1_scalar_tables.py /tmp/fvid-av1
"""
import ast, pathlib, re, sys, hashlib
base=sys.argv[1]
sources={n:pathlib.Path(base+'-'+n+'.md').read_text() for n in ['tables','parsing','decoding']}
out=['//! Normative AV1 tables. Generated by scripts/generate_av1_scalar_tables.py.']
for n,s in sources.items():out.append('//! '+n+' SHA-256: '+hashlib.sha256(s.encode()).hexdigest())
def emit(section,name):
 s=sources[section];m=re.search(r'^\s*'+name+r'\s*(?:\[[^\]]+\]\s*)+=\s*\{',s,re.M)
 assert m,name
 start=m.end()-1;end=start+1;depth=1
 while depth:depth+=(s[end]=='{')-(s[end]=='}');end+=1
 raw=re.sub(r'/\*.*?\*/|//[^\n]*','',s[start:end],flags=re.S)
 data=ast.literal_eval(raw.replace('{','[').replace('}',']'))
 def ty(v):
  if isinstance(v,int):return 'i32'
  inner=ty(v[0]);assert all(ty(x)==inner for x in v)
  return '['+inner+';'+str(len(v))+']'
 out.append('pub const '+name.upper()+': '+ty(data)+' = '+str(data)+';')
for name in re.findall(r'^(Default_Scan_\w+)\s*\[',sources['tables'],re.M):emit('tables',name)
for name in ['Sm_Weights_Tx_4x4','Sm_Weights_Tx_8x8','Sm_Weights_Tx_16x16','Sm_Weights_Tx_32x32','Sm_Weights_Tx_64x64','Dr_Intra_Derivative','Intra_Filter_Taps']:emit('tables',name)
for name in ['Dc_Qlookup','Ac_Qlookup','Subpel_Filters','Warped_Filters','Div_Lut']:emit('decoding',name)
emit('parsing','Coeff_Base_Ctx_Offset')
pathlib.Path('src/codec/av1_tables.rs').write_text('\n'.join(out)+'\n')
