#!/usr/bin/env python3
"""Translate AV1 normative quantizer data, separately from offline builds/tests.
Source: https://raw.githubusercontent.com/AOMediaCodec/av1-spec/master/10.additional.tables.md
Usage: generate_av1_quant_matrix_tables.py saved-additional-tables.md
"""
import ast, hashlib, re, sys
from pathlib import Path
source = Path(sys.argv[1]).read_text()

def array(name):
    match = re.search(r'^' + name + r'\s*(?:\[[^\]]+\]\s*)+=\s*\{', source, re.M)
    assert match, name
    start = match.end() - 1
    end, depth = start + 1, 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    raw = re.sub(r'/\*.*?\*/|//[^\n]*', '', source[start:end], flags=re.S)
    return ast.literal_eval(raw.replace('{', '[').replace('}', ']'))

matrices = array('Quantizer_Matrix')
offsets = array('Qm_Offset')
shapes = list(zip(array('Tx_Width'), array('Tx_Height')))
assert len(matrices) == 15 and len(offsets) == len(shapes) == 19
stride = len(matrices[0][0])
assert stride == 3344
assert all(len(level) == 2 and all(len(plane) == stride for plane in level) for level in matrices)
weights = bytes(v for level in matrices for plane in level for v in plane)
assert len(weights) == 15 * 2 * stride
for offset, (width, height) in zip(offsets, shapes):
    assert offset + min(width, 32) * min(height, 32) <= stride
root = Path(__file__).resolve().parents[1] / 'src/codec'
(root / 'av1_quant_matrix.bin').write_bytes(weights)
(root / 'av1_quant_matrix.rs').write_text('''//! Normative AV1 quantizer weights; generated by generate_av1_quant_matrix_tables.py.
//! Source SHA-256: ''' + hashlib.sha256(source.encode()).hexdigest() + '''
//! Data SHA-256: ''' + hashlib.sha256(weights).hexdigest() + '''
const WEIGHTS: &[u8; ''' + str(len(weights)) + '''] = include_bytes!("av1_quant_matrix.bin");
const OFFSETS: [usize; 19] = ''' + repr(offsets) + ''';
const SHAPES: [[usize; 2]; 19] = ''' + repr([list(s) for s in shapes]) + ''';
/// Coefficients and transform dimensions have already been validated by the caller.
pub(super) fn weights(level: u8, chroma: bool, size: [usize; 2]) -> &'static [u8] {
    let index = SHAPES.iter().position(|s| *s == size).expect("validated AV1 transform");
    let offset = (usize::from(level) * 2 + usize::from(chroma)) * ''' + str(stride) + ''' + OFFSETS[index];
    let length = size[0].min(32) * size[1].min(32);
    &WEIGHTS[offset..offset + length]
}
''')
print(len(weights), 'normative quantizer bytes saved')
