#!/usr/bin/env python3
"""Owned 32x32 flat AV1 timing/frame-ID/show-existing synthetic streams."""
import argparse,hashlib,json,subprocess
from pathlib import Path
class Bits:
    def __init__(self):self.bits=[]
    def u(self,v,n=1):self.bits.extend((v>>i)&1 for i in range(n-1,-1,-1))
    def bytes(self,trailing=False):
        if trailing:self.u(1)
        while len(self.bits)%8:self.u(0)
        return bytes(sum(self.bits[i+j]<<(7-j) for j in range(8)) for i in range(0,len(self.bits),8))
def leb(n):
    out=[]
    while True:
        v=n&127;n>>=7;out.append(v|(128 if n else 0))
        if not n:return bytes(out)
def obu(kind,payload):return bytes([(kind<<3)|2])+leb(len(payload))+payload

def sequence(ids,model,equal,width=5,delta_bits=2,order_bits=0,interintra=False):
    b=Bits();b.u(0,3);b.u(0);b.u(0);b.u(int(model))
    if model:
        b.u(1,32);b.u(30,32);b.u(int(equal))
        if equal:b.u(1) # uvlc(0), one tick per picture
        b.u(1);b.u(7,5);b.u(1,32);b.u(7,5);b.u(7,5)
    b.u(0);b.u(0,5);b.u(0,12);b.u(0,5)
    if model:b.u(0)
    b.u(4,4);b.u(4,4);b.u(31,5);b.u(31,5);b.u(int(ids))
    if ids:b.u(delta_bits-2,4);b.u(width-delta_bits-1,3)
    # 64x64 superblocks, no filter intra, intra edge filter; no inter tools.
    for value in [0,0,1,int(interintra),0,0,0]:b.u(value)
    b.u(int(order_bits>0))
    if order_bits:b.u(0);b.u(0) # joint compound, reference motion fields
    b.u(0);b.u(0) # force screen-content tools off
    if order_bits:b.u(order_bits-1,3)
    b.u(0);b.u(0);b.u(0) # superres, CDEF, restoration
    # 8-bit non-monochrome, unspecified colour, limited range, 4:2:0.
    b.u(0);b.u(0);b.u(0);b.u(0);b.u(0,2);b.u(0);b.u(0)
    return obu(1,b.bytes(True))

def hidden(ids,model,equal,frame_id,kind,slot,width=5):
    b=Bits();b.u(0);b.u(kind,2);b.u(0);b.u(1);b.u(1);b.u(0)
    if ids:b.u(frame_id,width)
    b.u(0) # no size override; no order hint or primary ref for intra
    if model:b.u(0) # no removal times
    b.u(255 if kind==0 else 1<<slot,8);b.u(0);b.u(0);b.u(1)
    b.u(0,8)
    for _ in range(6):b.u(0) # Y/U deltas, matrix, segmentation, reduced tx set
    # This entropy payload is the owned lossless flat fixture, generated by
    # scripts/av1_fixture.c. No private parameters or samples are used.
    return obu(6,b.bytes()+bytes([0x2e,0x03,0x80]))

def show(ids,model,equal,frame_id,slot,width=5):
    b=Bits();b.u(1);b.u(slot,3)
    if model and not equal:b.u(173,8)
    if ids:b.u(frame_id,width)
    return obu(3,b.bytes(True))

def webm(data):
    from generate_audio_resample_window_fixture import ebml
    packets=[];at=0;seq=b'';pending=b''
    while at<len(data):
        begin=at;kind=data[at]>>3;at+=1;size=0;shift=0
        while True:
            byte=data[at];at+=1;size|=(byte&127)<<shift;shift+=7
            if not byte&128:break
        payload_start=at;at+=size;piece=data[begin:at]
        if kind==1:seq=piece;pending+=piece
        elif kind in [3,6]:packets.append((pending+piece,kind==6 and not (data[payload_start]&16)));pending=b''
    header=ebml('1a45dfa3',ebml('4282',b'webm'))
    track=ebml('d7',b'\x01')+ebml('83',b'\x01')+ebml('86',b'V_AV1')+ebml('63a2',bytes([0x81,0,0,0])+seq)
    track+=ebml('23e383',(20000000).to_bytes(4,'big'))+ebml('e0',ebml('b0',bytes([32]))+ebml('ba',bytes([32])))
    cluster=ebml('e7',b'\x00')
    for i,(packet,hidden_frame) in enumerate(packets):cluster+=ebml('a3',b'\x81'+(i*20).to_bytes(2,'big')+bytes([(128 if i==0 else 0)|(8 if hidden_frame else 0)])+packet)
    segment=ebml('1549a966',ebml('2ad7b1',(1000000).to_bytes(3,'big')))+ebml('1654ae6b',ebml('ae',track))+ebml('1f43b675',cluster)
    return header+ebml('18538067',segment)

def main():
    args=argparse.ArgumentParser(description=__doc__);args.add_argument('--oracle',type=Path);args=args.parse_args()
    root=Path(__file__).resolve().parents[1]/'tests/fixtures/playback-errors';records=[]
    for name,ids,model,equal in [('plain',False,False,False),('id',True,False,False),('time',False,True,False),('time-id',True,True,False),('equal',False,True,True),('equal-id',True,True,True)]:
        for kind in [0,2]:
            for slot in [0,7]:
                prefix=sequence(ids,model,equal)+hidden(ids,model,equal,7,0,slot)
                if kind==2:prefix+=hidden(ids,model,equal,8,2,slot)
                packet=show(ids,model,equal,8 if kind==2 else 7,slot)
                data=prefix+packet+(packet if kind==2 else b'')
                filename=f'av1-show-existing-{name}-'+('key' if kind==0 else 'intra')+f'-slot{slot}.obu'
                (root/filename).write_bytes(data)
                records.append(dict(file=filename,sha256=hashlib.sha256(data).hexdigest(),shown=1 if kind==0 else 2))
    for name,old,current in [('window-edge',7,11),('window-wrap',30,1)]:
        data=sequence(True,False,False)+hidden(True,False,False,old,0,0)+hidden(True,False,False,current,2,0)+show(True,False,False,old,7)
        filename=f'av1-show-existing-{name}.obu';(root/filename).write_bytes(data)
        records.append(dict(file=filename,sha256=hashlib.sha256(data).hexdigest(),shown=1))
    refusals=[]
    def refusal(name,prefix,packet,error):
        data=prefix+packet;filename=f'av1-show-existing-invalid-{name}.obu';(root/filename).write_bytes(data)
        refusals.append(dict(file=filename,sha256=hashlib.sha256(data).hexdigest(),error=error))
    prefix=sequence(True,True,False)+hidden(True,True,False,7,0,0)
    refusal('id-mismatch',prefix,show(True,True,False,8,0),'AV1 show-existing frame ID does not match reference')
    prefix=sequence(True,False,False)+hidden(True,False,False,7,0,0)+hidden(True,False,False,16,2,0)
    refusal('stale-id',prefix,show(True,False,False,7,7),'AV1 show-existing frame ID does not match reference')
    prefix=sequence(False,True,False)+hidden(False,True,False,7,0,0)
    refusal('truncated-time',prefix,obu(3,bytes([128])),'truncated or oversized bit field')
    packet=bytearray(show(False,True,False,7,0));packet[-1]&=~8
    refusal('missing-trailing',prefix,bytes(packet),'missing AV1 frame header trailing bit')
    packet=bytearray(show(False,True,False,7,0));packet[-1]|=1
    refusal('nonzero-trailing',prefix,bytes(packet),'nonzero AV1 frame header trailing bits')
    packet=bytearray(show(False,True,False,7,0));packet[0]=(6<<3)|2
    refusal('wrong-obu-kind',prefix,bytes(packet),'AV1 show-existing requires frame header OBU')
    prefix=sequence(True,False,False)+hidden(True,False,False,7,0,0)
    refusal('truncated-id',prefix,obu(3,bytes([128])),'truncated or oversized bit field')
    for record in records[:24]:
        data=webm((root/record['file']).read_bytes());filename=record['file'].replace('.obu','.webm');(root/filename).write_bytes(data)
        record['webm']=filename;record['webm_sha256']=hashlib.sha256(data).hexdigest()
    if args.oracle:
        for record in records:subprocess.run([str(args.oracle),str(root/record['file']),str(record['shown'])],check=True)
    (root/'av1-show-existing-generated.json').write_text(json.dumps(dict(generator='owned flat AV1 show-existing timing/frame IDs',fixtures=records,refusals=refusals),indent=2)+'\n')
if __name__=='__main__':main()
