#!/usr/bin/env python3
"""Extract normative probability constants from the VP9 v0.7 PDF (requires pypdf)."""
import ast
import hashlib
import re
import sys
from pathlib import Path
from pypdf import PdfReader

source = Path(sys.argv[1])
text = '\n'.join(page.extract_text(extraction_mode='layout') for page in PdfReader(source).pages)
text = '\n'.join(line for line in text.splitlines() if 'Copyright' not in line and 'VP9 Bitstream & Decoding Process Specification' not in line)
tables = {
    'subpel_filters': (4,16,8),
    'pareto_table': (128, 8),
    'kf_partition_probs': (16, 3),
    'kf_y_mode_probs': (10, 10, 9),
    'kf_uv_mode_probs': (10, 9),
    'dc_qlookup': (3, 256),
    'ac_qlookup': (3, 256),
    **{f'{kind}_scan_{size}x{size}': (size*size,) for size in [4,8,16] for kind in ['default','row','col']},
    'default_scan_32x32': (1024,),
    'inv_map_table': (255,),
    'default_partition_probs': (16, 3),
    'default_y_mode_probs': (4, 9),
    'default_uv_mode_probs': (10, 9),
    'default_skip_prob': (3,),
    'default_is_inter_prob': (4,),
    'default_comp_mode_prob': (5,),
    'default_comp_ref_prob': (5,),
    'default_single_ref_prob': (5, 2),
    'default_mv_sign_prob': (2,),
    'default_mv_bits_prob': (2, 10),
    'default_mv_class0_bit_prob': (2,),
    'default_tx_probs': (4, 2, 3),
    'default_inter_mode_probs': (7, 3),
    'default_interp_filter_probs': (4, 2),
    'default_mv_joint_probs': (3,),
    'default_mv_class_probs': (2, 10),
    'default_mv_class0_fr_probs': (2, 2, 3),
    'default_mv_class0_hp_prob': (2,),
    'default_mv_fr_probs': (2, 3),
    'default_mv_hp_prob': (2,),
    'default_coef_probs': (4, 2, 2, 6, 6, 3),
}
output = '// Normative VP9 v0.7 sections 6.3.5 and 10.5. Generated by scripts/generate_vp9_tables.py.\n'
output += '// Source SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest() + '\n'
for name, dims in tables.items():
    match = re.search(r'\b' + name + r'(?:\s*\[[^\]]*\])+\s*=\s*\{', text, re.S)
    assert match, name
    start = match.end() - 1
    depth = 0
    for end in range(start, len(text)):
        if text[end] == '{': depth += 1
        if text[end] == '}': depth -= 1
        if depth == 0: break
    raw = re.sub(r'/\*.*?\*/|//[^\n]*', '', text[start:end+1], flags=re.S)
    raw = re.sub(r'(?<=\d)\s+(?=\d)', '', raw)
    raw = raw.replace('{','[').replace('}',']')
    value = ast.literal_eval(raw)
    def validate(v, ds):
        if not ds: assert isinstance(v,int) and -32768 <= v <= 65535; return
        assert len(v) == ds[0], (name,ds,len(v))
        for sub in v: validate(sub,ds[1:])
    validate(value,dims)
    ty = 'i16' if name == 'subpel_filters' else 'u16' if '_scan_' in name or '_qlookup' in name else 'u8'
    for d in reversed(dims): ty = f'[{ty}; {d}]'
    output += f'pub const {name.upper()}: {ty} = {value};\n'
Path('src/codec/vp9_tables.rs').write_text(output)
