#!/usr/bin/env python3
import json,pathlib,statistics,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
idx=json.load(open(ROOT/'research/source-index.json'))
notes={
'FFmpeg/FFmpeg':('Базовая линия, которую нельзя упрощать','Scheduler описывает DAG с проверкой циклов и ограничениями синхронизации. Обычный crop сдвигает plane pointers, vflip меняет stride; AVFrame использует reference-counted storage.','Перенять представления кадров и дисциплину drain; улучшать проверяемость контрактов, диагностику и explain.','Не утверждать, что FFmpeg копирует каждый фильтр или не имеет планировщика. Наличие этих механизмов ещё не доказывает оптимальность каждого сценария.'),
'GStreamer/gstreamer':('Пулы и многомерные лимиты очередей','gstbufferpool описывает предварительное выделение и возврат буферов; gstqueue ограничивает bytes, buffers и time, блокирует producer или применяет выбранный drop policy.','Единый бюджет памяти плюс лимиты на каждую очередь; в runtime нужны события EOS/flush и backpressure.','Локальные лимиты сами по себе не доказывают глобального потолка памяти и отсутствия deadlock.'),
'vapoursynth/vapoursynth':('Контракты зависимостей фильтра','API содержит VSFilterDependency, request patterns, режимы параллельности, запросы конкретных кадров и настройки cache history/size.','Пусть temporal-фильтры объявляют диапазон зависимостей; preview запрашивает нужное поколение и кадр.','Не выводить из API эффективность внутреннего scheduler: просмотрен интерфейс, не весь исполнитель.'),
'pdeljanov/Symphonia':('Раздельные временные типы и буферизация I/O','units.rs различает Timestamp, Duration, Delta и timebase; MediaSourceStream документирует ограниченный read-ahead и возможность backtracking для nonseekable источника.','Разделить типы времени, сделать возможности источника явными, подключать codecs/formats выборочно.','Полный codec corpus не запускался. Заявления README о скорости не переносим в свои результаты.'),
'MetalPetal/MetalPetal':('Оптимизация графа с учётом зависимостей','Optimizer строит node table, учитывает dependents и cache policy, вызывает специализированные объединения color matrix/compositing, перестраивает dependencies. Promise имеет dependencies, dimensions и alpha type.','Небольшие доказуемые rewrite rules; отличать transient и persistent результаты; учитывать fan-out.','Это специализированные правила, а не произвольное безопасное объединение всех GPU-операций.'),
'BabitMF/bmf':('Устройство как часть контракта кадра','VideoFrame имеет device, copy_ и to(device, non_blocking); документация to различает передачу устройства и разделение уже находящихся там данных. SchedulerQueue предоставляет очередь задач и pause/resume.','Явные upload/download и события готовности; стоимость переноса входит в placement.','Производственные масштабы и скорость из README — заявления авторов, здесь не проверенные. Из header очереди не следует global memory bound.'),
'software-mansion/smelter':('GPU-декодирование и порядок показа','WgpuTexturesDecoder выдаёт NV12 textures; FrameSorter использует metadata PTS/picture order и отдельный flush.','Разделить ready/decode/display order; GPU storage проходит через граф без обязательной CPU-материализации.','Не проверяли на устройстве ни этот backend, ни возможность совместного использования с VideoToolbox.'),
'chromeos/cros-codecs':('Surface lifetime и смена формата','FramePool учитывает минимальное число кадров; события различают FrameReady/FormatChanged; DecodedHandle имеет is_ready/sync. PooledVaSurface возвращается в существующий совместимый pool при Drop.','Учитывать DPB и поколение формата; держать ресурс до завершения fence и последнего пользователя.','Проект ориентирован на Linux. Нельзя автоматически перенести его API и гарантии на macOS.'),
'Vanilagy/mediabunny':('Обратное давление до encoder и writer','media-source.ts ожидает dequeue при заполнении encoder queue и lastMuxerPromise для writer backpressure; явно закрывает кадры. Conversion API различает transforms, codec options и сохранение rotation metadata.','Состояния жизненного цикла и backpressure входят в публичный контракт; высокоуровневый API строит тот же план.','WebCodecs — внешняя реализация кодеков; чистый TypeScript не означает, что сами кодеки написаны на TypeScript.'),
'membraneframework/membrane_core':('Demand вместо неограниченного производства','ManualFlowController обрабатывает demand/redemand, откладывает повторные запросы; InputQueue хранит размер и единицы demand.','Явное количество разрешённых данных и метрики очереди; ограничить циклы перепланирования.','Не копировать процессную/actor модель буквально для каждого Rust-фильтра; supervision ещё требует отдельного дизайна.'),
'BillyDM/Firewheel':('Расписание и буферы готовятся до обработки','CompiledSchedule хранит назначения buffers и возможность их переиспользования; sync_new_buffers документирует отсутствие allocation при безопасном reuse. process.rs обрабатывает звук блоками.','Скомпилированный план и preallocation; control plane отдельно от realtime callback.','Исходники используют raw pointers и unsafe в горячих участках. Это источник архитектуры, не свидетельство полностью safe-Rust исполнения.'),
'rust-av/Av1an':('Параллелизм по частям задания','Broker распределяет chunks через bounded channel, обрабатывает ошибки encoder и записывает завершённые части в done.json; диапазоны chunk используют exclusive end.','Checkpoint по завершённым независимым частям, ограничение worker concurrency, явные границы.','Нужны отдельные проверки швов, GOP, идентичности настроек и аудиосинхронизации. README-ускорения не воспроизведены.'),
'cool-japan/oximedia':('Матрица зрелости важнее числа функций','codec_status.md различает фактические режимы и историю их проверок. В просмотренном crop_plane выделяется новый Vec и копируются pixels, с fallback 0 при отсутствующем sample.','Вести capability matrix по профилям; Unsupported не должен становиться фальшивым успехом. Crop-view в Fvid следует проверить отдельно.','Не считать большой README или число tests доказательством замены FFmpeg. Наблюдение о crop относится только к указанному файлу/версии, а не всему проекту.'),
'rust-av/rust-av':('Общая модель данных отдельно от codec API','data/src/frame.rs содержит общие frame types и errors; codec/src/lib.rs разделяет common/decoder/encoder/error модули.','Переиспользуемые core primitives без зависимости от CLI; единый контракт для нескольких backend.','По структуре модулей нельзя заключить о полноте кодеков или скорости; дополнительно требуется поддержка нужных profiles.'),
'mozilla/mp4parse-rust':('Отказоустойчивое выделение памяти парсера','MP4 parser использует fallible_collections/TryVec/TryRead и проверяемые числовые преобразования; источник явно отделяет типы для fallible allocation.','Ограничить размеры, вложенность и объём parse work; ошибки allocation выражать в результате.','Просмотр выбранных участков не является полным security-аудитом и не доказывает отсутствие panic.'),
'halide/Halide':('Алгоритм и способ вычисления — разные решения','Учебный исходник на одном producer/consumer показывает inline, compute_root, compute_at, store и tiling.','LogicalPlan хранит семантику, PhysicalPlan выбирает материализацию и порядок вычисления.','Сам Halide не внедрён и его скорость здесь не измерялась. Собственный JIT не нужен в первом срезе.'),
'libvips/libvips':('Обработка нужного региона','generate.c описывает start/generate/stop sequence и per-thread input regions; генератор заполняет requested output region.','Тайлы/регионы и ленивое вычисление там, где это поддерживает операция; bounded cache.','Это библиотека изображений. Stateful video codec нельзя произвольно превратить в региональный декодер.'),
'AcademySoftwareFoundation/OpenTimelineIO':('Временная шкала монтажного проекта','RationalTime хранит value/rate и умеет rescale, но оба значения представлены double.','Явная time scale и диапазоны на уровне timeline; адаптация в точное внутреннее время двигателя.','Не приписывать OTIO целочисленную рациональную точность. Timeline interchange не заменяет media runtime.')}
lines=['# Что перенять: предметные наблюдения','', 'Просмотрены выбранные архитектурные участки 33 файлов из 18 проектов. Это не полный аудит этих репозиториев. Наблюдение отделено от предлагаемого решения. Все ссылки ниже закреплены на commit; копии и хеши доступны в source-index.json. Чужие исходники не включены в сборку Fvid.','']
for i,(repo,(title,fact,take,limit)) in enumerate(notes.items(),1):
 lines += [f'## {i}. {repo}: {title}','',f'**Наблюдение.** {fact}',f'**Для Fvid.** {take}',f'**Граница вывода.** {limit}','']
 for r in idx:
  if r['repository']==repo:lines.append(f"- [{r['file']}]({r['url']}) — commit `{r['commit'][:12]}`, {r['lines']} строк в сохранённом файле.")
 lines.append('')
lines += ['## Дополнительные первичные документы','', '- [GStreamer: общая архитектура](https://gstreamer.freedesktop.org/documentation/additional/design/overview.html): negotiation, clock, события и push/pull.', '- [GStreamer: buffer pool](https://gstreamer.freedesktop.org/documentation/additional/design/bufferpool.html).', '- [FFmpeg: send/receive и drain](https://ffmpeg.org/doxygen/trunk/group__lavc__encdec.html).', '- [VapourSynth API](https://www.vapoursynth.com/doc/apireference.html).','', 'Документация дополняет исходники; live-страницы могут изменяться. Структурные гипотезы не заменяют измерений.']
(ROOT/'research/FINDINGS.md').write_text('\n'.join(lines)+'\n')
r=json.load(open(ROOT/'benchmarks/results.json'))
lines=['# Fvid против FFmpeg: фактические измерения','',f"Дата UTC: {r['created_utc']}. Платформа: {r['platform']} / {r['machine']}. CPU model: {r['cpu']}. Версии: {r['ffmpeg']}; {r['rustc']}.",'','Проверка: 12 комбинаций формата/операции (420/422/444 × copy/hflip/vflip/crop+hflip+vflip), по 7 кадров. Сравнены размеры, число кадров и SHA-256 декодированных planar payload всех трёх вариантов. Совпало побайтно. Это небольшой синтетический корпус, не conformance suite.','', 'Бенчмарк: 720p/180 кадров, 1080p/120, 4K/60; YUV420p testsrc2, чтение локального Y4M и запись Y4M в null sink. В каждой комбинации один прогрев и 7 раундов со случайным порядком трёх команд (seed 451). Тест CPU-only, warm cache, без кодирования в H.264/AV1, без GPU, без fsync. Замер включает startup процесса; интервалы короткие. RSS получен отдельно для каждого дочернего процесса через wait4, единицы macOS — байты. Модель CPU недоступна из sandbox; её не угадывали.','', 'Основная baseline — **FFmpeg с обычными настройками**, а не искусственно ограниченный одним потоком. Однопоточный вариант — дополнительный диагностический столбец.','', '| Размер / операция | Fvid, мс | FFmpeg default, мс | FFmpeg 1 thread, мс | default / Fvid | Fvid peak RSS, MiB | FFmpeg default peak RSS, MiB |','|---|---:|---:|---:|---:|---:|---:|']
for t in r['results']:
 m=t['median_seconds'];ratio=m['ffmpeg_default']/m['fvid'];rss=t['max_rss_bytes']
 lines.append(f"| {t['resolution']} {t['case']} | {m['fvid']*1000:.2f} | {m['ffmpeg_default']*1000:.2f} | {m['ffmpeg_1thread']*1000:.2f} | {ratio:.2f}× | {max(rss['fvid'])/2**20:.1f} | {max(rss['ffmpeg_default'])/2**20:.1f} |")
lines += ['', 'Число >1 означает, что Fvid завершился быстрее; <1 — FFmpeg быстрее. RSS в таблице — максимум семи запусков; время — медиана. Это сравнение целых CLI, не отдельного kernel.','', '## Вывод','', 'Прототип выигрывает часть коротких задач и комбинированный crop+отражения, но проигрывает FFmpeg default в 4K copy/hflip/vflip. Поэтому результаты не подтверждают общий тезис «Rust быстрее FFmpeg». Простота запуска и упаковки тоже влияет на измерение. Ни новый codec, ни универсальное преимущество scheduler здесь не проверялись.','', 'FFmpeg уже умеет crop/vflip через frame views. Текущий Fvid всегда материализует выходной frame buffer. Следующая осмысленная гипотеза — убрать эту копию там, где downstream допускает view, и отдельно измерить длительную обработку в памяти.','', '## Воспроизведение','', '```sh','cargo build --release','python3 scripts/benchmark.py','python3 scripts/write_reports.py','```','', 'Нужны Rust, Python 3, FFmpeg; RSS-часть сценария использует POSIX wait4, приведённые единицы интерпретированы для macOS. `benchmarks/results.json` содержит все 252 индивидуальных времени (12×3×7), RSS, версии, точные команды и 12 контрольных подписей. Входы восстанавливаются из указанных команд testsrc2; их хеши и хеши локального Rust-кода записаны в provenance.json. После изменения исходников требуется новая сборка и новый запуск.','', '## Что ещё не измерено','', '- Длительная установившаяся скорость и confidence intervals; cold cache/физический диск, pipe-to-pipe и durable output.', '- H.264/HEVC/AV1/AAC, качество на одинаковом битрейте, другие типы видеоматериала.', '- GPU, переносы поверхностей, задержка live, масштабирование scheduler.', '- Другие ОС/процессоры и сравнение с выбранными 632 проектами. Они исследованы как источники архитектурных решений, а не пробенчмарканы.']
(ROOT/'benchmarks/REPORT.md').write_text('\n'.join(lines)+'\n')
provenance={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [ROOT/'Cargo.toml',ROOT/'Cargo.lock',*sorted((ROOT/'src').glob('*.rs')),*sorted((ROOT/'benchmarks/data').glob('*.y4m'))]}
(ROOT/'benchmarks/provenance.json').write_text(json.dumps(provenance,indent=2))
print('Written research/FINDINGS.md and benchmarks/REPORT.md')
