//! Numeric protocol geometry: GOST R 53556.8-2013 tables 45/46/48/49.
//! Generated explicitly/offline by generate_aac_ps_mapping_tables.py.
use super::aac_ps_mapping::Binding;
pub(super) const UP: &[(&[(u8, u8)], u8)] = &[
    (&[(0, 1)], 1),
    (&[(0, 1), (1, 1)], 2),
    (&[(1, 1)], 1),
    (&[(2, 1)], 1),
    (&[(2, 1), (3, 1)], 2),
    (&[(3, 1)], 1),
    (&[(4, 1)], 1),
    (&[(4, 1)], 1),
    (&[(5, 1)], 1),
    (&[(5, 1)], 1),
    (&[(6, 1)], 1),
    (&[(7, 1)], 1),
    (&[(8, 1)], 1),
    (&[(8, 1)], 1),
    (&[(9, 1)], 1),
    (&[(9, 1)], 1),
    (&[(10, 1)], 1),
    (&[(11, 1)], 1),
    (&[(12, 1)], 1),
    (&[(13, 1)], 1),
    (&[(14, 1)], 1),
    (&[(14, 1)], 1),
    (&[(15, 1)], 1),
    (&[(15, 1)], 1),
    (&[(16, 1)], 1),
    (&[(16, 1)], 1),
    (&[(17, 1)], 1),
    (&[(17, 1)], 1),
    (&[(18, 1)], 1),
    (&[(18, 1)], 1),
    (&[(18, 1)], 1),
    (&[(18, 1)], 1),
    (&[(19, 1)], 1),
    (&[(19, 1)], 1),
];
pub(super) const DOWN: &[(&[(u8, u8)], u8)] = &[
    (&[(0, 2), (1, 1)], 3),
    (&[(1, 1), (2, 2)], 3),
    (&[(3, 2), (4, 1)], 3),
    (&[(4, 1), (5, 2)], 3),
    (&[(6, 1), (7, 1)], 2),
    (&[(8, 1), (9, 1)], 2),
    (&[(10, 1)], 1),
    (&[(11, 1)], 1),
    (&[(12, 1), (13, 1)], 2),
    (&[(14, 1), (15, 1)], 2),
    (&[(16, 1)], 1),
    (&[(17, 1)], 1),
    (&[(18, 1)], 1),
    (&[(19, 1)], 1),
    (&[(20, 1), (21, 1)], 2),
    (&[(22, 1), (23, 1)], 2),
    (&[(24, 1), (25, 1)], 2),
    (&[(26, 1), (27, 1)], 2),
    (&[(28, 1), (29, 1), (30, 1), (31, 1)], 4),
    (&[(32, 1), (33, 1)], 2),
];
pub(super) const HYBRID_20: &[Binding] = &[
    Binding {
        qmf: 0,
        parameter: 1,
        conjugate: true,
    },
    Binding {
        qmf: 0,
        parameter: 0,
        conjugate: true,
    },
    Binding {
        qmf: 0,
        parameter: 0,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 1,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 2,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 3,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 4,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 5,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 6,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 7,
        conjugate: false,
    },
    Binding {
        qmf: 3,
        parameter: 8,
        conjugate: false,
    },
    Binding {
        qmf: 4,
        parameter: 9,
        conjugate: false,
    },
    Binding {
        qmf: 5,
        parameter: 10,
        conjugate: false,
    },
    Binding {
        qmf: 6,
        parameter: 11,
        conjugate: false,
    },
    Binding {
        qmf: 7,
        parameter: 12,
        conjugate: false,
    },
    Binding {
        qmf: 8,
        parameter: 13,
        conjugate: false,
    },
    Binding {
        qmf: 9,
        parameter: 14,
        conjugate: false,
    },
    Binding {
        qmf: 10,
        parameter: 14,
        conjugate: false,
    },
    Binding {
        qmf: 11,
        parameter: 15,
        conjugate: false,
    },
    Binding {
        qmf: 12,
        parameter: 15,
        conjugate: false,
    },
    Binding {
        qmf: 13,
        parameter: 15,
        conjugate: false,
    },
    Binding {
        qmf: 14,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 15,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 16,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 17,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 18,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 19,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 20,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 21,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 22,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 23,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 24,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 25,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 26,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 27,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 28,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 29,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 30,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 31,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 32,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 33,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 34,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 35,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 36,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 37,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 38,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 39,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 40,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 41,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 42,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 43,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 44,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 45,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 46,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 47,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 48,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 49,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 50,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 51,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 52,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 53,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 54,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 55,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 56,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 57,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 58,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 59,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 60,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 61,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 62,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 63,
        parameter: 19,
        conjugate: false,
    },
];
pub(super) const HYBRID_34: &[Binding] = &[
    Binding {
        qmf: 0,
        parameter: 0,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 1,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 2,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 3,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 4,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 5,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 6,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 6,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 7,
        conjugate: false,
    },
    Binding {
        qmf: 0,
        parameter: 2,
        conjugate: true,
    },
    Binding {
        qmf: 0,
        parameter: 1,
        conjugate: true,
    },
    Binding {
        qmf: 0,
        parameter: 0,
        conjugate: true,
    },
    Binding {
        qmf: 1,
        parameter: 10,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 10,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 4,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 5,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 6,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 7,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 8,
        conjugate: false,
    },
    Binding {
        qmf: 1,
        parameter: 9,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 10,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 11,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 12,
        conjugate: false,
    },
    Binding {
        qmf: 2,
        parameter: 9,
        conjugate: false,
    },
    Binding {
        qmf: 3,
        parameter: 14,
        conjugate: false,
    },
    Binding {
        qmf: 3,
        parameter: 11,
        conjugate: false,
    },
    Binding {
        qmf: 3,
        parameter: 12,
        conjugate: false,
    },
    Binding {
        qmf: 3,
        parameter: 13,
        conjugate: false,
    },
    Binding {
        qmf: 4,
        parameter: 14,
        conjugate: false,
    },
    Binding {
        qmf: 4,
        parameter: 15,
        conjugate: false,
    },
    Binding {
        qmf: 4,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 4,
        parameter: 13,
        conjugate: false,
    },
    Binding {
        qmf: 5,
        parameter: 16,
        conjugate: false,
    },
    Binding {
        qmf: 6,
        parameter: 17,
        conjugate: false,
    },
    Binding {
        qmf: 7,
        parameter: 18,
        conjugate: false,
    },
    Binding {
        qmf: 8,
        parameter: 19,
        conjugate: false,
    },
    Binding {
        qmf: 9,
        parameter: 20,
        conjugate: false,
    },
    Binding {
        qmf: 10,
        parameter: 21,
        conjugate: false,
    },
    Binding {
        qmf: 11,
        parameter: 22,
        conjugate: false,
    },
    Binding {
        qmf: 12,
        parameter: 22,
        conjugate: false,
    },
    Binding {
        qmf: 13,
        parameter: 23,
        conjugate: false,
    },
    Binding {
        qmf: 14,
        parameter: 23,
        conjugate: false,
    },
    Binding {
        qmf: 15,
        parameter: 24,
        conjugate: false,
    },
    Binding {
        qmf: 16,
        parameter: 24,
        conjugate: false,
    },
    Binding {
        qmf: 17,
        parameter: 25,
        conjugate: false,
    },
    Binding {
        qmf: 18,
        parameter: 25,
        conjugate: false,
    },
    Binding {
        qmf: 19,
        parameter: 26,
        conjugate: false,
    },
    Binding {
        qmf: 20,
        parameter: 26,
        conjugate: false,
    },
    Binding {
        qmf: 21,
        parameter: 27,
        conjugate: false,
    },
    Binding {
        qmf: 22,
        parameter: 27,
        conjugate: false,
    },
    Binding {
        qmf: 23,
        parameter: 27,
        conjugate: false,
    },
    Binding {
        qmf: 24,
        parameter: 28,
        conjugate: false,
    },
    Binding {
        qmf: 25,
        parameter: 28,
        conjugate: false,
    },
    Binding {
        qmf: 26,
        parameter: 28,
        conjugate: false,
    },
    Binding {
        qmf: 27,
        parameter: 29,
        conjugate: false,
    },
    Binding {
        qmf: 28,
        parameter: 29,
        conjugate: false,
    },
    Binding {
        qmf: 29,
        parameter: 29,
        conjugate: false,
    },
    Binding {
        qmf: 30,
        parameter: 30,
        conjugate: false,
    },
    Binding {
        qmf: 31,
        parameter: 30,
        conjugate: false,
    },
    Binding {
        qmf: 32,
        parameter: 30,
        conjugate: false,
    },
    Binding {
        qmf: 33,
        parameter: 31,
        conjugate: false,
    },
    Binding {
        qmf: 34,
        parameter: 31,
        conjugate: false,
    },
    Binding {
        qmf: 35,
        parameter: 31,
        conjugate: false,
    },
    Binding {
        qmf: 36,
        parameter: 31,
        conjugate: false,
    },
    Binding {
        qmf: 37,
        parameter: 32,
        conjugate: false,
    },
    Binding {
        qmf: 38,
        parameter: 32,
        conjugate: false,
    },
    Binding {
        qmf: 39,
        parameter: 32,
        conjugate: false,
    },
    Binding {
        qmf: 40,
        parameter: 32,
        conjugate: false,
    },
    Binding {
        qmf: 41,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 42,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 43,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 44,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 45,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 46,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 47,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 48,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 49,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 50,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 51,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 52,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 53,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 54,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 55,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 56,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 57,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 58,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 59,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 60,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 61,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 62,
        parameter: 33,
        conjugate: false,
    },
    Binding {
        qmf: 63,
        parameter: 33,
        conjugate: false,
    },
];
